---
- name: DEPLOYMENT ON EKS
  hosts: k8s
  remote_user: root
  tasks:  
    - name: CREATE PLAYBOOKS DIR ON EKS CLUSTER
      file:
        path: /opt/playbooks/
        state: directory
        mode: "0755"   
    - name: COPY DEPLOYMENT FILE
      copy:
        src: /var/lib/jenkins/workspace/k8s/playbooks/pod.yaml
        dest: /opt/playbooks
    - name: CHECK FILE
      shell: ls -l /opt/playbooks/
      register: copy        

    - name: DEPLOYMENT FILE COPY STATUS      
      debug:
        var: copy.stdout_lines              
        
    - name: DEPLOYMENT ON K8 CLUSTER
      shell: kubectl apply -f /opt/playbooks/pod.yaml
      register: deployment

    - name: DEPLOYMENT STATUS      
      debug:
        var: deployment.stdout_lines

    - name: WAITING FOR GET DEPLOYMENT STATUS
      shell: sleep 10     

    - name: STATUS OF DEPLOYMENT
      shell: kubectl get pod
      register: get_deployment_status
      
    - name: STATUS OF SERVICE
      shell: kubectl get svc
      register: get_svc_status

    - name: PRINT DEPLOYMENT STATUS
      debug:
        var: get_deployment_status.stdout_lines
